### ISSUE TITLE
Announce more supported media formats in .desktop file?

### ISSUE THREAD

**Issue by petterreinholdtsen** [ukui/kylin-video#17]
According to the README, the player support most formats, but when looking at the MIME types announced in the .desktop file, quite a few are missing.  This will cause the Linux desktop environments to not propose the kylin video player when encountering several audio and video files.  Perhaps the .desktop file should be amended to list more MIME types?

A list of MIME types listed in the .desktop files of other media players available in Debian unstable is available from https://wiki.debian.org/DebianMultimedia/PlayerSupport .  Perhaps it can provide inspiration on the MIME types to add to the .desktop file?

**Comment by handsome-feng** [comment]
Hi,  @petterreinholdtsen , sorry for the delay, we will update the list in .desktop recently. Thanks a lot for your suggestion!

**Comment by zhao-yubiao** [comment]
Have already add，thank you for your advice.
